using System;
using System.Windows.Forms;
using Microsoft.Win32;

namespace LicenseParser
{
    // This class handles the background C# code which goes hand-in-hand with the user preferences form. Its main tasks are writing
    // to the CURRENT_USER registry where the preferences are stored and proccessing the user's various changes on the page.
    public partial class PrefsForm : Form
    {
        // comment content variables
        private static bool addComments = true;
        private static bool showFeatureTypes = false;
        private static bool showLicenseTypes = false;
        private static bool showNumberOfSeats = false;
        private static bool listSubComponents = false;

        // comment formatting variables
        private static char commentChar = '#';
        private static int leadingCommentSpace = 1;
        private static bool indentedComments = false;
        private static int indentSpaces = 4;

        // header formatting variables
        private static char headerChar = '=';
        private static bool commentHeaders = true;
        private static bool fixedHeaderLength = false;
        private static bool variableHeaderLength = true;
        private static int fixedCommentLength = 10;

        // misc. variables
        private static bool keepComments = false;
        private static bool keepBreaks = false;
        private static string licenseMetaXMLPath = "";

        // Accessors for all of the above variables.
        // Since other classes need to know the user prefs for parsing but can't access the values of the checkboxes/etc.
        // directly from the preferences form, we need these private variables with accessors to make the prefs available.
        public static int FixedCommentLength { get => fixedCommentLength; }
        public static bool VariableHeaderLength { get => variableHeaderLength; }
        public static bool FixedHeaderLength { get => fixedHeaderLength; }
        public static bool CommentHeaders { get => commentHeaders; }
        public static bool KeepBreaks { get => keepBreaks; }
        public static bool KeepComments { get => keepComments; }
        public static string LicenseMetaXMLPath { get => licenseMetaXMLPath; }
        public static int IndentSpaces { get => indentSpaces; }
        public static bool ListSubComponents { get => listSubComponents; }
        public static bool ShowNumberOfSeats { get => showNumberOfSeats; }
        public static bool ShowLicenseTypes { get => showLicenseTypes; }
        public static bool ShowFeatureTypes { get => showFeatureTypes; }
        public static bool IndentedComments { get => indentedComments; }
        public static char CommentChar { get => commentChar; }
        public static char HeaderChar { get => headerChar; }
        public static int LeadingCommentSpace { get => leadingCommentSpace; }
        public static bool AddComments { get => addComments; }

        // Autogenerated constructor required for Designer support in Visual Studio
        public PrefsForm()
        {
            InitializeComponent();
        }

        // Restores all form objects, registry values, and class variables to their default values.
        // Called when there is a problem / missing value found when attempting to access the registry.
        public void CreateDefault()
        {
            RegistryKey rkHKCU = Registry.CurrentUser;
            RegistryKey rkRun;

            showFeatureTypes = false;
            showLicenseTypes = false;
            showNumberOfSeats = false;
            listSubComponents = false;

            commentChar = '#';
            headerChar = '=';
            leadingCommentSpace = 1;
            indentSpaces = 4;

            licenseMetaXMLPath = "";

            indentedComments = false;
            keepComments = false;
            keepBreaks = false;
            addComments = true;
            commentHeaders = true;
            fixedHeaderLength = false;
            variableHeaderLength = true;
            fixedCommentLength = 10;

            rkRun = recurse(rkHKCU);
            rkRun.SetValue("KeepComments", keepComments);
            rkRun.SetValue("KeepBreaks", keepBreaks);
            rkRun.SetValue("AddComments", addComments);
            rkRun.SetValue("FeatureTypes", showFeatureTypes);
            rkRun.SetValue("LicenseTypes", showLicenseTypes);
            rkRun.SetValue("NumOfSeats", showNumberOfSeats);
            rkRun.SetValue("SubComponents", listSubComponents);
            rkRun.SetValue("Headers", commentHeaders);
            rkRun.SetValue("FixedLength", fixedHeaderLength);
            rkRun.SetValue("VariableLength", variableHeaderLength);
            rkRun.SetValue("FixedNumber", fixedCommentLength);
            rkRun.SetValue("FixedNumberEnabled", fixedHeaderLength);
            rkRun.SetValue("HeaderChar", headerChar);
            rkRun.SetValue("CommentChar", commentChar);
            rkRun.SetValue("SpaceAfterCommentChar", leadingCommentSpace);
            rkRun.SetValue("IndentedComments", indentedComments);
            rkRun.SetValue("SpacesInIndent", indentSpaces);
            rkRun.SetValue("SpacesInIndentEnabled", indentedComments);
            rkRun.SetValue("LicenseMetaXMLPath", licenseMetaXMLPath);

            featureTypes.Checked = false;
            licenseTypes.Checked = false;
            numberSeats.Checked = false;
            subComponents.Checked = false;
            commentCharBox.Text = "#";
            headerCharBox.Text = "=";
            leadingCommentSpaceVal.Value = 1;
            numberOfSpacesPerIndent.Value = 4;
            numberOfSpacesPerIndent.Enabled = false;
            indentedCommentsBox.Checked = false;
            comments2.Checked = false;
            linebreaks2.Checked = false;
            addCommentsBox.Checked = true;
            headers.Checked = true;
            fixedLength.Checked = false;
            variableLength.Checked = true;
            fixedNumber.Visible = false;
            fixedNumber.Value = 10;

            XMLPathBox.Text = "";

            rkHKCU.Close();
            rkRun.Close();
        }

        public static void StartUp()
        {
            try
            {
                RegistryKey rkHKCU = Registry.CurrentUser;
                RegistryKey key = originalRecurse(rkHKCU);
                RegistryKey rkRun = key;
                keepComments = Convert.ToBoolean(rkRun.GetValue("KeepComments").ToString());
                keepBreaks = Convert.ToBoolean(rkRun.GetValue("KeepBreaks").ToString());
                addComments = Convert.ToBoolean(rkRun.GetValue("AddComments").ToString());
                showFeatureTypes = Convert.ToBoolean(rkRun.GetValue("FeatureTypes").ToString());
                showLicenseTypes = Convert.ToBoolean(rkRun.GetValue("LicenseTypes").ToString());
                showNumberOfSeats = Convert.ToBoolean(rkRun.GetValue("NumOfSeats").ToString());
                listSubComponents = Convert.ToBoolean(rkRun.GetValue("SubComponents").ToString());
                commentHeaders = Convert.ToBoolean(rkRun.GetValue("Headers").ToString());
                fixedHeaderLength = Convert.ToBoolean(rkRun.GetValue("FixedLength").ToString());
                variableHeaderLength = Convert.ToBoolean(rkRun.GetValue("VariableLength").ToString());
                fixedCommentLength = Convert.ToInt32(rkRun.GetValue("FixedNumber").ToString());
                headerChar = (char)rkRun.GetValue("HeaderChar").ToString()[0];
                commentChar = (char)rkRun.GetValue("CommentChar").ToString()[0];
                leadingCommentSpace = Convert.ToInt32(rkRun.GetValue("SpaceAfterCommentChar").ToString());
                indentedComments = Convert.ToBoolean(rkRun.GetValue("IndentedComments").ToString());
                indentSpaces = Convert.ToInt32(rkRun.GetValue("SpacesInIndent").ToString());

                licenseMetaXMLPath = rkRun.GetValue("LicenseMetaXMLPath").ToString();
            }
            catch (NullReferenceException e)
            {
                showFeatureTypes = false;
                showLicenseTypes = false;
                showNumberOfSeats = false;
                listSubComponents = false;

                commentChar = '#';
                headerChar = '=';
                leadingCommentSpace = 1;
                indentSpaces = 4;

                indentedComments = false;
                keepComments = false;
                keepBreaks = false;
                addComments = true;
                commentHeaders = true;
                fixedHeaderLength = false;
                variableHeaderLength = true;
                fixedCommentLength = 10;

                licenseMetaXMLPath = "";
            }
        }

        public void Open()
        {
            try
            {
                RegistryKey rkHKCU = Registry.CurrentUser;
                RegistryKey key = recurse(rkHKCU);
                RegistryKey rkRun = key;
                comments2.Checked = Convert.ToBoolean(rkRun.GetValue("KeepComments").ToString());
                linebreaks2.Checked = Convert.ToBoolean(rkRun.GetValue("KeepBreaks").ToString());
                addCommentsBox.Checked = Convert.ToBoolean(rkRun.GetValue("AddComments").ToString());
                featureTypes.Checked = Convert.ToBoolean(rkRun.GetValue("FeatureTypes").ToString());
                licenseTypes.Checked = Convert.ToBoolean(rkRun.GetValue("LicenseTypes").ToString());
                numberSeats.Checked = Convert.ToBoolean(rkRun.GetValue("NumOfSeats").ToString());
                subComponents.Checked = Convert.ToBoolean(rkRun.GetValue("SubComponents").ToString());
                headers.Checked = Convert.ToBoolean(rkRun.GetValue("Headers").ToString());
                fixedLength.Checked = Convert.ToBoolean(rkRun.GetValue("FixedLength").ToString());
                variableLength.Checked = Convert.ToBoolean(rkRun.GetValue("VariableLength").ToString());
                fixedNumber.Value = Convert.ToInt32(rkRun.GetValue("FixedNumber").ToString());
                fixedNumber.Visible = Convert.ToBoolean(rkRun.GetValue("FixedNumberEnabled").ToString());
                headerCharBox.Text = rkRun.GetValue("HeaderChar").ToString();
                commentCharBox.Text = rkRun.GetValue("CommentChar").ToString();
                leadingCommentSpaceVal.Value = Convert.ToInt32(rkRun.GetValue("SpaceAfterCommentChar").ToString());
                indentedCommentsBox.Checked = Convert.ToBoolean(rkRun.GetValue("IndentedComments").ToString());
                numberOfSpacesPerIndent.Value = Convert.ToInt32(rkRun.GetValue("SpacesInIndent").ToString());
                if (addCommentsBox.Checked)
                {
                    numberOfSpacesPerIndent.Enabled = Convert.ToBoolean(rkRun.GetValue("SpacesInIndentEnabled").ToString());
                }
                else
                {
                    numberOfSpacesPerIndent.Enabled = false;
                }
                leadingCommentSpaceVal.Enabled = addCommentsBox.Checked;
                commentContent.Enabled = addCommentsBox.Checked;
                headerOptions.Enabled = addCommentsBox.Checked;
                indentedCommentsBox.Enabled = addCommentsBox.Checked;
                headerLengthBox.Enabled = headers.Checked;

                XMLPathBox.Text = rkRun.GetValue("LicenseMetaXMLPath").ToString();

                rkRun.Close();

                key.Close();
                rkHKCU.Close();
            }
            catch (NullReferenceException e)
            {
                MessageBox.Show("One or more of the stored values for user preferences was found to be missing from the registry. Preferences have been reset to their default values.");
                this.CreateDefault();
            }
        }

        public void Save()
        {
            RegistryKey rkHKCU = Registry.CurrentUser;
            RegistryKey rkRun = recurse(rkHKCU);
            rkRun.SetValue("KeepComments", comments2.Checked);
            rkRun.SetValue("KeepBreaks", linebreaks2.Checked);
            rkRun.SetValue("AddComments", addCommentsBox.Checked);
            rkRun.SetValue("FeatureTypes", featureTypes.Checked);
            rkRun.SetValue("LicenseTypes", licenseTypes.Checked);
            rkRun.SetValue("NumOfSeats", numberSeats.Checked);
            rkRun.SetValue("SubComponents", subComponents.Checked);
            rkRun.SetValue("Headers", headers.Checked);
            rkRun.SetValue("FixedLength", fixedLength.Checked);
            rkRun.SetValue("VariableLength", variableLength.Checked);
            rkRun.SetValue("FixedNumber", fixedNumber.Value);
            rkRun.SetValue("FixedNumberEnabled", fixedNumber.Visible);
            rkRun.SetValue("HeaderChar", headerCharBox.Text);
            rkRun.SetValue("CommentChar", commentCharBox.Text);
            rkRun.SetValue("SpaceAfterCommentChar", leadingCommentSpaceVal.Value);
            rkRun.SetValue("IndentedComments", indentedCommentsBox.Checked);
            rkRun.SetValue("SpacesInIndent", numberOfSpacesPerIndent.Value);
            rkRun.SetValue("SpacesInIndentEnabled", numberOfSpacesPerIndent.Enabled);

            rkRun.SetValue("LicenseMetaXMLPath", XMLPathBox.Text);

            rkHKCU.Close();
            rkRun.Close();

            showFeatureTypes = featureTypes.Checked;
            keepComments = comments2.Checked;
            keepBreaks = linebreaks2.Checked;
            addComments = addCommentsBox.Checked;
            showLicenseTypes = licenseTypes.Checked;
            showNumberOfSeats = numberSeats.Checked;
            listSubComponents = subComponents.Checked;
            commentHeaders = headers.Checked;
            fixedHeaderLength = fixedLength.Checked;
            variableHeaderLength = variableLength.Checked;
            fixedCommentLength = (int)fixedNumber.Value;
            headerChar = (char)headerCharBox.Text[0];
            commentChar = (char)commentCharBox.Text[0];
            indentSpaces = (int)numberOfSpacesPerIndent.Value;
            indentedComments = indentedCommentsBox.Checked;
            leadingCommentSpace = (int)leadingCommentSpaceVal.Value;

            licenseMetaXMLPath = XMLPathBox.Text;

            MainMenu.displayFailure("Preferences saved.");
        }

        // Needed to save XML rename from parse click failure without re-saving everything
        public static void SetXML(String newPath)
        {
            licenseMetaXMLPath = newPath;
            RegistryKey rkHKCU = Registry.CurrentUser;
            RegistryKey rkRun = originalRecurse(rkHKCU);
            rkRun.SetValue("LicenseMetaXMLPath", LicenseMetaXMLPath);
        }

        private void addComments_Click(object sender, EventArgs e)
        {
            if (addCommentsBox.Checked)
            {
                headerOptions.Enabled = true;
                commentContent.Enabled = true;
                if (indentedCommentsBox.Checked)
                {
                    numberOfSpacesPerIndent.Enabled = true;
                }
                indentedCommentsBox.Enabled = true;
                leadingCommentSpaceVal.Enabled = true;
            }
            else
            {
                headerOptions.Enabled = false;
                commentContent.Enabled = false;
                numberOfSpacesPerIndent.Enabled = false;
                indentedCommentsBox.Enabled = false;
                leadingCommentSpaceVal.Enabled = false;
            }
            
        }

        private void fixedLength_Click(object sender, EventArgs e)
        {
            if (fixedLength.Checked)
            {
                fixedNumber.Visible = true;
            }
            
        }

        private void variableLength_Click(object sender, EventArgs e)
        {
            if (variableLength.Checked)
            {
                fixedNumber.Visible = false;
            }
            
        }

        private void headers_Click(object sender, EventArgs e)
        {
            if (headers.Checked)
            {
                headerLengthBox.Enabled = true;
            }
            else
            {
                headerLengthBox.Enabled = false;
            }
            
        }

        private void indentedComments_Click(object sender, EventArgs e)
        {
            if (indentedCommentsBox.Checked)
            {
                numberOfSpacesPerIndent.Enabled = true;
            }
            else
            {
                numberOfSpacesPerIndent.Enabled = false;
            }
            
        }

        private void XMLPathBox_TextChanged(object sender, EventArgs e)
        {
            licenseMetaXMLPath = XMLPathBox.Text;
        }

        private void reset_Click(object sender, EventArgs e)
        {
              showFeatureTypes = false;
              showLicenseTypes = false;
              showNumberOfSeats = false;
              listSubComponents = false;

              commentChar = '#';
              headerChar = '=';
              leadingCommentSpace = 1;
              indentSpaces = 4;

              indentedComments = false;
              keepComments = false;
              keepBreaks = false;
              addComments = true;
              commentHeaders = true;
              fixedHeaderLength = false;
              variableHeaderLength = true;
              fixedCommentLength = 10;

              featureTypes.Checked = false;
              licenseTypes.Checked = false;
              numberSeats.Checked = false;
              subComponents.Checked = false;
              commentCharBox.Text = "#";
              headerCharBox.Text = "=";
              leadingCommentSpaceVal.Value = 1;
              numberOfSpacesPerIndent.Value = 4;
              numberOfSpacesPerIndent.Enabled = false;
              indentedCommentsBox.Checked = false;
              comments2.Checked = false;
              linebreaks2.Checked = false;
              addCommentsBox.Checked = true;
              headers.Checked = true;
              fixedLength.Checked = false;
              variableLength.Checked = true;
              fixedNumber.Visible = false;
              fixedNumber.Value = 10;              
        }

        private void savePrefs_Click(object sender, EventArgs e)
        {
            this.Save();
            this.Close();
        }

        private RegistryKey recurse(RegistryKey reg)
        {
            RegistryKey rk = reg;
            RegistryKey temp = null;
            foreach (String s in reg.GetSubKeyNames())
            {
                if (s.Equals("Software") || s.Equals("SOFTWARE"))
                {
                    temp = reg.OpenSubKey(s, true);
                    temp = temp.CreateSubKey("MDi");
                    temp = temp.CreateSubKey("Flexnet License Parser");
                    temp = temp.CreateSubKey("1.0");
                    temp = temp.CreateSubKey("Prefs");
                    break;
                }
            }
            return temp;
        }

        private static RegistryKey originalRecurse(RegistryKey reg)
        {
            RegistryKey rk = reg;
            RegistryKey temp = null;
            foreach (String s in reg.GetSubKeyNames())
            {
                if (s.Equals("Software") || s.Equals("SOFTWARE"))
                {
                    temp = reg.OpenSubKey(s, true);
                    temp = temp.CreateSubKey("MDi");
                    temp = temp.CreateSubKey("Flexnet License Parser");
                    temp = temp.CreateSubKey("1.0");
                    temp = temp.CreateSubKey("Prefs");
                    break;
                }
            }
            return temp;
        }

        private void cancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void selectXML_Click(object sender, EventArgs e)
        {
            OpenFileDialog openDialog = new OpenFileDialog();
            openDialog.Filter = "XML Files | *.xml";
            openDialog.ShowDialog();
            if (!string.IsNullOrEmpty(openDialog.FileName))
            {
                XMLPathBox.Text = openDialog.FileName;
            }
        }
    }
}
